services:
  app:
    build:
      context: .
      target: base
      platforms:
        - linux/arm64
    ports:
      - '3000:3000'
      - '5555:5555'
    depends_on:
      - db
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pronofootball?schema=public
    volumes:
      - .:/app
      - /app/.next
    command: npm run dev
    restart: unless-stopped

  db:
    image: postgres:15
    platform: linux/arm64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pronofootball
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

